# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('resources/icon.ico', 'resources/'), ('resources/icon.png', 'resources/'), ('resources/check.png', 'resources/')],
    hiddenimports=[
        'openpyxl.cell._writer',
        'openpyxl.cell.writer',
        # 功能模块与 worker 由 main.py / main_window.py 动态 import（惰性加载），
        # PyInstaller 的静态扫描看不到，必须显式声明，否则打包后会缺模块。
        'app.updater',
        'app.settings',
        'app.settings_dialog',
        'app.features.split',
        'app.features.merge',
        'app.features.dedup',
        'app.features.convert',
        'app.features.filter',
        'app.features.columns',
        'app.features.pivot',
        'app.features.validate',
        'core.reader',
        'core.splitter',
        'core.merger',
        'core.deduper',
        'core.converter',
        'core.filter_engine',
        'core.column_ops',
        'core.pivoter',
        'core.validator',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.QtWebEngine',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebChannel',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuickWidgets',
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DExtras',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtLocation',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtPdf',
        'PySide6.QtPdfWidgets',
        'PySide6.QtPrintSupport',
        'PySide6.QtSensors',
        'PySide6.QtSerialPort',
        'PySide6.QtSql',
        'PySide6.QtSvg',
        'PySide6.QtSvgWidgets',
        'PySide6.QtTest',
        'PySide6.QtTextToSpeech',
        'PySide6.QtXml',
        'PySide6.QtNetwork',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='GridFlow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/icon.png',
)
