"""配色常量"""

LIGHT_COLORS = {
    "PRIMARY": "#2563EB",
    "PRIMARY_HOVER": "#1D4ED8",
    "PRIMARY_LIGHT": "#DBEAFE",
    "SUCCESS": "#16A34A",
    "SUCCESS_LIGHT": "#DCFCE7",
    "DANGER": "#DC2626",
    "DANGER_LIGHT": "#FEE2E2",
    "WARNING": "#F59E0B",
    "BG_MAIN": "#F1F5F9",
    "BG_CARD": "#FFFFFF",
    "BG_INPUT": "#F8FAFC",
    "TEXT_PRIMARY": "#1E293B",
    "TEXT_SECONDARY": "#64748B",
    "TEXT_MUTED": "#94A3B8",
    "BORDER": "#E2E8F0",
    "BORDER_FOCUS": "#2563EB",
    "RADIUS_SM": "4",
    "RADIUS_MD": "8",
    "RADIUS_LG": "12",
}

DARK_COLORS = {
    "PRIMARY": "#3B82F6",
    "PRIMARY_HOVER": "#2563EB",
    "PRIMARY_LIGHT": "#1E3A5F",
    "SUCCESS": "#22C55E",
    "SUCCESS_LIGHT": "#14532D",
    "DANGER": "#EF4444",
    "DANGER_LIGHT": "#7F1D1D",
    "WARNING": "#F59E0B",
    "BG_MAIN": "#0F172A",
    "BG_CARD": "#1E293B",
    "BG_INPUT": "#334155",
    "TEXT_PRIMARY": "#F1F5F9",
    "TEXT_SECONDARY": "#94A3B8",
    "TEXT_MUTED": "#64748B",
    "BORDER": "#334155",
    "BORDER_FOCUS": "#3B82F6",
    "RADIUS_SM": "4",
    "RADIUS_MD": "8",
    "RADIUS_LG": "12",
}

# Legacy module-level aliases (for existing code that imports from theme directly)
PRIMARY = LIGHT_COLORS["PRIMARY"]
PRIMARY_HOVER = LIGHT_COLORS["PRIMARY_HOVER"]
PRIMARY_LIGHT = LIGHT_COLORS["PRIMARY_LIGHT"]
SUCCESS = LIGHT_COLORS["SUCCESS"]
SUCCESS_LIGHT = LIGHT_COLORS["SUCCESS_LIGHT"]
DANGER = LIGHT_COLORS["DANGER"]
DANGER_LIGHT = LIGHT_COLORS["DANGER_LIGHT"]
WARNING = LIGHT_COLORS["WARNING"]
BG_MAIN = LIGHT_COLORS["BG_MAIN"]
BG_CARD = LIGHT_COLORS["BG_CARD"]
BG_INPUT = LIGHT_COLORS["BG_INPUT"]
TEXT_PRIMARY = LIGHT_COLORS["TEXT_PRIMARY"]
TEXT_SECONDARY = LIGHT_COLORS["TEXT_SECONDARY"]
TEXT_MUTED = LIGHT_COLORS["TEXT_MUTED"]
BORDER = LIGHT_COLORS["BORDER"]
BORDER_FOCUS = LIGHT_COLORS["BORDER_FOCUS"]
RADIUS_SM = LIGHT_COLORS["RADIUS_SM"]
RADIUS_MD = LIGHT_COLORS["RADIUS_MD"]
RADIUS_LG = LIGHT_COLORS["RADIUS_LG"]
